// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonP5Fj3pcST9vCt1fyxnr2Bm0k14WMfE',
    appId: '1:201453586081:web:5ce3b4b0b58fcb72f252e0',
    messagingSenderId: '201453586081',
    projectId: 'chat-app-flutter-2278f',
    authDomain: 'chat-app-flutter-2278f.firebaseapp.com',
    storageBucket: 'chat-app-flutter-2278f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivk1M2VJatLjVzgeq4g425WG1Vc08KuM',
    appId: '1:201453586081:android:15a3b294c20ae10ef252e0',
    messagingSenderId: '201453586081',
    projectId: 'chat-app-flutter-2278f',
    storageBucket: 'chat-app-flutter-2278f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDbkt65wksjs6H8cirOl4O1F-xY1CvL8',
    appId: '1:201453586081:ios:164ee55397da898ef252e0',
    messagingSenderId: '201453586081',
    projectId: 'chat-app-flutter-2278f',
    storageBucket: 'chat-app-flutter-2278f.appspot.com',
    iosClientId: '201453586081-pc7d018c422dh0kf5ek2as999f2e0r3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDbkt65wksjs6H8cirOl4O1F-xY1CvL8',
    appId: '1:201453586081:ios:248ed51fc821ceabf252e0',
    messagingSenderId: '201453586081',
    projectId: 'chat-app-flutter-2278f',
    storageBucket: 'chat-app-flutter-2278f.appspot.com',
    iosClientId: '201453586081-fat9uk3hl7mvncqj8d1ku3ks4cu2osjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutterFirebase.RunnerTests',
  );
}
